# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mafia.proto',
  package='mafia',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmafia.proto\x12\x05mafia\"!\n\x0eUpdatesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x1e\n\x0bGameRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\";\n\x12GameSearchResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x14\n\x0cis_status_ok\x18\x02 \x01(\x08\"6\n\x12\x43hatMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x14RequestProcessStatus\x12\x14\n\x0cis_status_ok\x18\x01 \x01(\x08\"\xc5\x01\n\x06Update\x12\x0f\n\x07message\x18\x01 \x01(\t\x12/\n\x0bupdate_code\x18\x02 \x01(\x0e\x32\x1a.mafia.Update.UpdateStatus\"y\n\x0cUpdateStatus\x12\x0c\n\x08NEW_USER\x10\x00\x12\x0f\n\x0bNEW_MESSAGE\x10\x01\x12\x0e\n\nUSERS_LIST\x10\x02\x12\x15\n\x11GAME_SEARCH_START\x10\x03\x12\x16\n\x12GAME_SEARCH_FINISH\x10\x04\x12\x0b\n\x07NOTHING\x10\x05\x32\x93\x02\n\x0bMafiaServer\x12:\n\x0eReceiveUpdates\x12\x15.mafia.UpdatesRequest\x1a\r.mafia.Update\"\x00\x30\x01\x12;\n\x08\x46indGame\x12\x12.mafia.GameRequest\x1a\x19.mafia.GameSearchResponse\"\x00\x12K\n\x0fSendChatMessage\x12\x19.mafia.ChatMessageRequest\x1a\x1b.mafia.RequestProcessStatus\"\x00\x12>\n\tLeaveGame\x12\x12.mafia.GameRequest\x1a\x1b.mafia.RequestProcessStatus\"\x00\x62\x06proto3'
)



_UPDATE_UPDATESTATUS = _descriptor.EnumDescriptor(
  name='UpdateStatus',
  full_name='mafia.Update.UpdateStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW_USER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USERS_LIST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_SEARCH_START', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_SEARCH_FINISH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTHING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=329,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_UPDATE_UPDATESTATUS)


_UPDATESREQUEST = _descriptor.Descriptor(
  name='UpdatesRequest',
  full_name='mafia.UpdatesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='mafia.UpdatesRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=55,
)


_GAMEREQUEST = _descriptor.Descriptor(
  name='GameRequest',
  full_name='mafia.GameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='mafia.GameRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=87,
)


_GAMESEARCHRESPONSE = _descriptor.Descriptor(
  name='GameSearchResponse',
  full_name='mafia.GameSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='mafia.GameSearchResponse.game_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_status_ok', full_name='mafia.GameSearchResponse.is_status_ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=148,
)


_CHATMESSAGEREQUEST = _descriptor.Descriptor(
  name='ChatMessageRequest',
  full_name='mafia.ChatMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='mafia.ChatMessageRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='mafia.ChatMessageRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=204,
)


_REQUESTPROCESSSTATUS = _descriptor.Descriptor(
  name='RequestProcessStatus',
  full_name='mafia.RequestProcessStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_status_ok', full_name='mafia.RequestProcessStatus.is_status_ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=250,
)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='mafia.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='mafia.Update.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_code', full_name='mafia.Update.update_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPDATE_UPDATESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=450,
)

_UPDATE.fields_by_name['update_code'].enum_type = _UPDATE_UPDATESTATUS
_UPDATE_UPDATESTATUS.containing_type = _UPDATE
DESCRIPTOR.message_types_by_name['UpdatesRequest'] = _UPDATESREQUEST
DESCRIPTOR.message_types_by_name['GameRequest'] = _GAMEREQUEST
DESCRIPTOR.message_types_by_name['GameSearchResponse'] = _GAMESEARCHRESPONSE
DESCRIPTOR.message_types_by_name['ChatMessageRequest'] = _CHATMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['RequestProcessStatus'] = _REQUESTPROCESSSTATUS
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdatesRequest = _reflection.GeneratedProtocolMessageType('UpdatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESREQUEST,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.UpdatesRequest)
  })
_sym_db.RegisterMessage(UpdatesRequest)

GameRequest = _reflection.GeneratedProtocolMessageType('GameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEREQUEST,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.GameRequest)
  })
_sym_db.RegisterMessage(GameRequest)

GameSearchResponse = _reflection.GeneratedProtocolMessageType('GameSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESEARCHRESPONSE,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.GameSearchResponse)
  })
_sym_db.RegisterMessage(GameSearchResponse)

ChatMessageRequest = _reflection.GeneratedProtocolMessageType('ChatMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGEREQUEST,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.ChatMessageRequest)
  })
_sym_db.RegisterMessage(ChatMessageRequest)

RequestProcessStatus = _reflection.GeneratedProtocolMessageType('RequestProcessStatus', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPROCESSSTATUS,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.RequestProcessStatus)
  })
_sym_db.RegisterMessage(RequestProcessStatus)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.Update)
  })
_sym_db.RegisterMessage(Update)



_MAFIASERVER = _descriptor.ServiceDescriptor(
  name='MafiaServer',
  full_name='mafia.MafiaServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=453,
  serialized_end=728,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveUpdates',
    full_name='mafia.MafiaServer.ReceiveUpdates',
    index=0,
    containing_service=None,
    input_type=_UPDATESREQUEST,
    output_type=_UPDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindGame',
    full_name='mafia.MafiaServer.FindGame',
    index=1,
    containing_service=None,
    input_type=_GAMEREQUEST,
    output_type=_GAMESEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendChatMessage',
    full_name='mafia.MafiaServer.SendChatMessage',
    index=2,
    containing_service=None,
    input_type=_CHATMESSAGEREQUEST,
    output_type=_REQUESTPROCESSSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LeaveGame',
    full_name='mafia.MafiaServer.LeaveGame',
    index=3,
    containing_service=None,
    input_type=_GAMEREQUEST,
    output_type=_REQUESTPROCESSSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAFIASERVER)

DESCRIPTOR.services_by_name['MafiaServer'] = _MAFIASERVER

# @@protoc_insertion_point(module_scope)
